### ISSUE TITLE
Não está rodando :c 

### ISSUE THREAD

**Issue by samanthaeufrasio** [mbcalisto/whatever#2]
https://github.com/mbcalisto/whatever/blob/5e1d567fdeab2a67d204b980091fb29c42ee8fb5/whatever/main.swift#L103

Adorei o código, programa legal, mas infelizmente não rodou no meu computador. Ele afirma que não possui as variáveis no scopo

**Comment by kipras-pal** [comment]
Tive o mesmo problema, não consigo rodar
